---
title: "Chapter 2: Statistical Modeling"
output: html_notebook
---

<body>
      <font face = "Times New Roman">
  
<p id="0"><u><font size="5"><b>Table of contents</b></font></u></p>  
<a href="#1">[1]</a> Statistical Modeling
<br> &emsp; <a href="#2">[1.1]</a> The difference between statistical and probabilistic models
<br> &emsp; <a href="#3">[1.2]</a> A simple example of statistical modeling
<br> &emsp; <a href="#4">[1.3]</a> Classical statistics for classical data
<br> &emsp; <a href="#5">[1.4]</a> Binomial distributions and maximum likelihood
<br> &emsp; <a href="#6">[1.5]</a> More boxes:multinomial data
<br> &emsp; <a href="#7">[1.6]</a> The χ<sup>2</sup> distribution
<br> &emsp; <a href="#8">[1.7]</a> Chargaff’s Rule
<br> &emsp; <a href="#9">[1.8]</a> Example: occurrence of a nucleotide pattern in a genome
<br> &emsp; <a href="#10">[1.9]</a> Bayesian Thinking
<br> &emsp; <a href="#11">[2.0]</a> Excercises</br> 
<a href="#x">[X]</a> Misc.

* **

<p id="1"><b><font size="5">Statistical Modeling</b></font><a href="#0"><sup>Return</sup></a></p>

* **

<p id="1"><b><font size="5">Statistical Modeling</b></font><a href="#0"><sup>Return</sup></a></p>

* **
<p id="2"><b><font size="5">The difference between statistical and probabilistic models</b></font><a href="#0"><sup>Return</sup></a></p>

* **
<p id="3"><b><font size="5">A simple example of statistical modeling</b></font><a href="#0"><sup>Return</sup></a></p>

* **
<p id="4"><b><font size="5">Classical statistics for classical data</b></font><a href="#0"><sup>Return</sup></a></p>

* **
<p id="5"><b><font size="5">Binomial distributions and maximum likelihood</b></font><a href="#0"><sup>Return</sup></a></p>

* **
<p id="6"><b><font size="5">More boxes:multinomial data</b></font><a href="#0"><sup>Return</sup></a></p>

* **
<p id="7"><b><font size="5">he χ<sup>2</sup> distribution</b></font><a href="#0"><sup>Return</sup></a></p>

* **
<p id="8"><b><font size="5">Chargaff’s Rule</b></font><a href="#0"><sup>Return</sup></a></p>

* **
<p id="9"><b><font size="5">Example: occurrence of a nucleotide pattern in a genome</b></font><a href="#0"><sup>Return</sup></a></p>

* **
<p id="10"><b><font size="5">Bayesian Thinking</b></font><a href="#0"><sup>Return</sup></a></p>

* **
<p id="11"><b><font size="5">Excercises</b></font><a href="#0"><sup>Return</sup></a></p>


* **

<p id="x"><b><font size="5">Miscellaneous</b></font><a href="#0"><sup>Return</sup></a></p>

*Run* = *Ctrl+Shift+Enter*  
*Insert Chunk* =*Ctrl+Alt+I*  
*Preview*=*Ctrl+Shift+K*

</body>
  